# Basic
title: KUKA YouBot Development
subtitle: Long Ding
description: keep hungry and keep fool!
# 头像里面的标题
avatarTitle: Adangge
# 头像里面的描述
avatarDesc: Love what is lovely!
url: "https://adangge.github.io"

# Comment
    disqus: adangge.github.io
    comments: true
 
value:
   author: Long Ding
   comments: true
   share: true
   
# Social
social:
    QQ: 754157977
    github: Adangge
    # twitter: 
    mail: ding_longcslg@hotmail.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:


# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:

    host:  


# ----------------- 上面的信息修改成你自己的 ---------------------------
#
#  _post/   文章目录
#  _drafts/ 未发布的文章目录
#  目录结构具体参考文档：http://jekyll.com.cn/docs/structure/
#
# --------------- 下面的信息可以自行选择是否修改 ------------------------


permalink: /:year/:month/:title/
# Format
markdown: kramdown
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear #背景Mask

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 存档, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


